import time
while True:
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("ROFL:ROFL:LOL:         ")
    print("          _^___")
    print(" L    __/   []  \ ")
    print(" O ===__         \ ")
    print(" L      \_________]")
    print("          I   I")
    print("        --------/")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    time.sleep(0.15)
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("         :LOL:ROFL:ROFL")
    print("          _^___")
    print("      __/   []  \ ")
    print("LOL===__         \ ")
    print("        \_________]")
    print("          I   I")
    print("        --------/")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    time.sleep(0.15)